### ISSUE TITLE
Voting on important issues

### ISSUE THREAD

**Issue by arirawr** [HackathonHackers/org#6]
There is no structure for a group of people to vote and decide on bans, controversial content, etc. With only one person given the power to ban, that decision is left unilateral.

**Comment by rubinovitz** [comment]
Actually I think this is deceptively worse than it appears:

"There is only one active admin, though the creator of the group exists on the panel, only to ensure that no newly added admin ever reaches a point where they refuse to give up ownership of the group when their term has ended."

The one active admin actually does not have that power, it's the "creator" since the "creator" can kick the active admin at any time and the active admin cannot kick the creator.
